### ISSUE TITLE
5.5.Write a program which accept number from user and return difference between summation of all its factors and non factors.

### ISSUE THREAD

**Issue by Ektaaa28** [Ektaaa28/Logic-Building#23]
Write a c program which accept a number from user and display difference between sum of factors and non-factors of this number.
for example,If user input **12** then output is **sum of its factors(16)-sum of its non factors(50)=-34**.

NOTE:Save this program in **Assignment5** and name of this program should be **Assignment5_5.c**

**Comment by Mohit-Chaudhari** [comment]
@Ektaaa28 what is the problem with this issue???

What help you want ???

**Comment by Mohit-Chaudhari** [comment]
https://www.hitbullseye.com/Quant/Factors-Number.php

This link may help you for this issue.

**Comment by Ektaaa28** [comment]
Problem was solved
