### ISSUE TITLE
3.1.Write a program which accept one number from user and print that number of even numbers on screen.

### ISSUE THREAD

**Issue by Ektaaa28** [Ektaaa28/Logic-Building#9]
Write a c program to accept one number from user and print that number of even numbers on screen.
For example : If input of user is **8**  then print **first 8 even numbers** i.e,**2 4 6 8 10 12 14 16**.

 NOTE: Save this program in **Assignment3** and the name of this program should be **Assignment3_1.c**

**Comment by Mohit-Chaudhari** [comment]
What is the difficulty for this issue. Why are u not taking this issue for resolution???

**Comment by Mohit-Chaudhari** [comment]
@Ektaaa28 what is difficulty for this issue ?

**Comment by Ektaaa28** [comment]
There was a slight problem in it but now it is solve.
